---
kind: pipeline
name: write-to-trenddb-amd64
type: docker

platform:
  os: linux
  arch: amd64

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - tag

steps:
  - name: push-amd64
    image: plugins/docker
    settings:
      registry: harbor.zkjgy.online
      repo: harbor.zkjgy.online/library/write-to-trenddb
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      tags:
        - linux-amd64
      dockerfile: Dockerfile
      context: .
    volumes:
      - name: docker
        path: /var/run/docker.sock

---
kind: pipeline
name: write-to-trenddb-arm64
type: docker

platform:
  os: linux
  arch: arm64

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - tag

steps:
  - name: push-arm64
    image: plugins/docker
    settings:
      registry: harbor.zkjgy.online
      repo: harbor.zkjgy.online/library/write-to-trenddb
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      tags:
        - linux-arm64
      dockerfile: Dockerfile
      context: .
    volumes:
      - name: docker
        path: /var/run/docker.sock

---
kind: pipeline
name: write-to-trenddb-manifest
type: docker

depends_on:
  - write-to-trenddb-amd64
  - write-to-trenddb-arm64

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - tag

steps:
  - name: manifest-latest
    image: plugins/manifest
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      target: harbor.zkjgy.online/library/write-to-trenddb:latest
      template: harbor.zkjgy.online/library/write-to-trenddb:OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64

---
kind: pipeline
name: write-to-trenddb-helm
type: docker

depends_on:
  - write-to-trenddb-manifest

trigger:
  branch:
    - main
  event:
    - push
    - tag

steps:
  - name: helm-package-push
    image: alpine/helm:3.14.0
    environment:
      HARBOR_USERNAME:
        from_secret: harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password
    commands:
      - helm registry login harbor.zkjgy.online
          --username $HARBOR_USERNAME
          --password $HARBOR_PASSWORD
      - helm package helm/write-to-trenddb --version 0.1.0
      - helm push write-to-trenddb-0.1.0.tgz oci://harbor.zkjgy.online/library
