apiVersion: v2
name: write-to-trenddb
description: 消费 MQTT 传感器数据并写入 TrendDB5 时序数据库的 .NET Worker Service
type: application
version: 2.6.1
appVersion: "2.6.1"
keywords:
  - iot
  - trenddb
  - mqtt
  - kubeedge
maintainers:
  - name: ganyu
